Upgrade DF to 36.0.0 and arrow-rs 50.0.0
apache/arrow-datafusion-comet pull request #66
Opened 2024-02-20 23:52 UTC by comphead

## Which issue does this PR close?

Closes #56.

## Rationale for this change

## What changes are included in this PR?

## How are these changes tested?

2024-02-21 00:36 UTC, viirya requested changes
Let's hold this until internal patches are ported to Comet. Thanks.

2024-02-21 07:11 UTC, viirya commented
Yea

2024-02-22 01:31 UTC, comphead commented
> I think we should wait for 36.0.1?

Just curious, what is so interesting in 36.0.1? 🤔

2024-02-22 02:33 UTC, viirya commented
I think @andygrove encountered circular dependency issue while releasing 36.0.0. So there is 36.0.1 after fixing the issue.

2024-02-25 17:38 UTC, sunchao commented
Looks like 36.0.1 is abandoned. Shall we move forward with this PR?

2024-02-26 00:11 UTC, viirya commented
Sounds good to me.

2024-02-26 00:12 UTC, viirya commented on core/src/execution/datafusion/expressions/scalar_funcs.rs
> +            dt => exec_err!("Not supported datatype[{dt}] for ROUND"),
Hm, why wrap `dt` with `[]`? I don't see there is something in Comet or DataFusion.

2024-02-27 03:45 UTC, viirya commented on core/src/execution/datafusion/expressions/scalar_funcs.rs
> +            dt => exec_err!("Not supported datatype[{dt}] for ROUND"),
```suggestion
            dt => exec_err!("Not supported datatype for ROUND: {dt}"),
```

2024-02-27 03:46 UTC, viirya commented on core/src/execution/datafusion/expressions/scalar_funcs.rs
> +            dt => exec_err!("Not supported datatype[{dt}] for ROUND"),
```suggestion
            dt => exec_err!("Not supported datatype for ROUND: {dt}"),
```

2024-02-27 22:49 UTC, viirya approved these changes

2024-02-27 22:54 UTC, sunchao approved these changes

2024-02-28 01:17 UTC, merged